spring.application.name=blockchain-service


#URL Eureka Server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# opsional: perpendek interval heartbeat
#eureka.instance.lease-renewal-interval-in-seconds=10
#eureka.instance.lease-expiration-duration-in-seconds=30

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port = 8081


# Konfigurasi Blockchain
web3j.client-address=http://127.0.0.1:7545
web3j.network-id=5777
# Wallet Ganache
wallet.private-key=0xac6c92fbd4e5d77f7668051da9de117afb8c9232c5f1a1a22ccdb0f8a9e21e51
# Alamat kontrak yang sudah dideploy di Ganache
contract.address=0x67b7FAF90A6C78F7D21705020955dE4E3CeAB39F


ipfs.host=127.0.0.1
ipfs.port=5001
ipfs.api.url= http://127.0.0.1:5001