spring.application.name=blockchain-service
server.port=8080

#URL Eureka Server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# opsional: perpendek interval heartbeat
#eureka.instance.lease-renewal-interval-in-seconds=10
#eureka.instance.lease-expiration-duration-in-seconds=30
#logging.level.com.netflix.discovery.shared.transport=ERROR
#logging.level.com.netflix.discovery=ERROR
#logging.level.com.netflix.eureka=ERROR
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false

#Servive
java.wrapper.path=src/main/java/com/blockchain/blockchain_service/contract
contract.path=src/main/resources/smartContract/build/contracts/
abi.bin.path=src/main/resources/smartContract/
contract.name=CustomerContract


#Blockchain
private.key=0x172c33318a78a9a8b0c1c570398449fa8394b98a4024801552247d631c426a37
contract.address=0xA8AD65730e492BfC4371E0c00e1B5b34EB000794

#Ganache
ganache.url=http://127.0.0.1:7545

#IPFS
ipfs.url.add=http://127.0.0.1:5001/api/v0/add
ipfs.url.get=http://localhost:5001/api/v0/cat?arg=
ipfs.url.pin=http://localhost:5001/api/v0/pin/add?
ipfs.url.unpin=http://localhost:5001/api/v0/pin/rm?
ipfs.url.list.cid=http://localhost:5001/api/v0/pin/ls
