spring.application.name=blockchain-service
server.port=8081

#URL Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# opsional: perpendek interval heartbeat
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
logging.level.com.netflix.discovery.shared.transport=ERROR
logging.level.com.netflix.discovery=ERROR
logging.level.com.netflix.eureka=ERROR
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

#Servive
folder.path=src/main/java/com/blockchain/blockchain_service/files
contract.path=src/main/java/com/blockchain/blockchain_service/contract

#Blockchain
private.key=e5790b8f08ec18b10adc7f33ae57b4ddc61f6bbf7d2d584cff8c359adaa0a415
contract.address=0xcB4fC990558126A69f31e8E0104323be6F0A83e3

#IPFS
ipfs.url=http://127.0.0.1:5001/api/v0/add